"""Search → signed selection → deadline-safe answer through the real HTTP boundary."""
import json
from uuid import uuid4
from fractions import Fraction

import pytest
from fastapi.testclient import TestClient

from backend.app import create_app
from backend.catalog.search import SongSearch
from backend.core.config import Config
from backend.core.errors import DomainError
from backend.game.scoring import half_up
from tests.integration.test_api import session, start
from tests.unit.test_song_catalog import SONG


def test_global_fixture_search_authentication_and_local_offline_selection(session):
    c, clock, host, guests, room, prefix, lease = session
    assert TestClient(host.app).get(prefix + '/song-search?q=Test').status_code == 401
    response = host.get(prefix + '/song-search', params={'q': 'Test Song 001'})
    assert response.status_code == 200, response.text
    result = response.json()
    assert result['source'] == 'catalog' and len(result['songs']) == 1
    chosen = result['songs'][0]
    assert set(chosen) == {'title', 'artist', 'artwork_url', 'token'}
    assert 'listener' not in response.text and 'preview_url' not in response.text
    gid, attempt, _ = start(session)
    with c.db.read() as conn:
        clock.value = c.game.repo.current(conn, gid)['starts_at_ms']
    c.tick()
    path = prefix + f'/games/{gid}/rounds/{attempt["id"]}/answers'
    payload = {'song_guess_token': chosen['token'], 'who_player_ids': []}
    assert host.post(path, json=payload).status_code == 200
    assert host.get(prefix + '/state').json()['game']['round']['my_answer']['song_guess']['title'] == 'Test Song 001'
    with c.db.read() as conn:
        answer = c.game.repo.answers(conn, attempt['id'])[0]
        guess = json.loads(answer['song_guess_json'])
        assert guess['title'] == 'Test Song 001' and guess['artists'][0]['artist_key'] == 'demo:test-artist-1'
        deadline = c.game.repo.current(conn, gid)['deadline_at_ms']
    clock.value = deadline
    assert host.post(path, json=payload).status_code == 200  # Identical retry after closure.
    revealed = host.get(prefix + '/state').json()['game']['round']['reveal']['my_answer']
    assert revealed['song_guess']['title'] == chosen['title']
    guest_reveal = guests[0].get(prefix + '/state').json()['game']['round']['reveal']
    assert 'answers' not in guest_reveal
    assert guest_reveal['my_answer']['song_guess'] is None


def test_selection_expiry_wrong_room_and_tampering_rejected_without_answer(session):
    c, clock, host, guests, room, prefix, lease = session
    chosen = host.get(prefix + '/song-search', params={'q': 'Test Song 001'}).json()['songs'][0]
    other = host.post('/api/rooms', json={'nickname': 'Other', 'mode': 'demo'}).json()
    token_other = host.get('/api/rooms/' + other['room_id'] + '/song-search', params={'q': 'Test Song 001'}).json()['songs'][0]['token']
    gid, attempt, _ = start(session)
    with c.db.read() as conn:
        clock.value = c.game.repo.current(conn, gid)['starts_at_ms']
    c.tick()
    path = prefix + f'/games/{gid}/rounds/{attempt["id"]}/answers'
    for token in (token_other, chosen['token'][:-1] + 'x'):
        response = host.post(path, json={'song_guess_token': token, 'who_player_ids': []})
        assert response.status_code == 400 and response.json()['error']['code'] == 'invalid_song_selection'
    # A genuine old selection with an expired timestamp; generated by the same server codec.
    router_search = host.app.state.song_search
    expired = router_search.tokens.issue(room['room_id'], SONG, clock.value - 1_200_001)
    response = host.post(path, json={'song_guess_token': expired, 'who_player_ids': []})
    assert response.status_code == 400 and response.json()['error']['code'] == 'song_selection_expired'
    with c.db.read() as conn:
        assert c.game.repo.answers(conn, attempt['id']) == []


def test_http_external_search_cache_metadata_and_outage(tmp_path):
    calls = []
    def provider(query):
        calls.append(query)
        if query == 'offline':
            raise DomainError('song_search_unavailable', 'Offline', 503)
        return [SONG]
    app = create_app(Config(tmp_path), background=False, song_search=SongSearch(provider))
    with TestClient(app) as client:
        room = client.post('/api/rooms', json={'nickname': 'Host', 'mode': 'demo'}).json()
        path = '/api/rooms/' + room['room_id'] + '/song-search'
        assert client.get(path, params={'q': 'Billie Jean'}).json()['source'] == 'apple'
        second = client.get(path, params={'q': 'billie jean'}).json()
        assert second['cached'] and second['songs'][0]['title'] == SONG['title']
        assert calls == ['billie jean']
        response = client.get(path, params={'q': 'offline'})
        assert response.status_code == 503 and response.json()['error']['retryable']
        assert client.get(path, params={'q': 'x'}).status_code == 400
        assert client.get(path, params={'q': 'x' * 101}).status_code == 400


def test_waveform_preload_metadata_reaches_round_without_playback_reference(session):
    c, clock, host, guests, room, prefix, lease = session
    state = host.get(prefix + '/state').json()
    gid = host.post(prefix + '/start', json={'request_id': str(uuid4()), 'room_revision': state['room']['revision'],
                                           'lease_id': lease}).json()['game_id']
    manifest = host.get(prefix + f'/games/{gid}/audio', headers={'X-Audio-Lease': lease}).json()
    levels = [0.1, 0.2, 0.6, 0.3, 0.9, 0.4, 0.2, 0.5]
    for candidate in manifest['candidates']:
        response = host.post(prefix + f'/games/{gid}/preload-check', json={'request_id': str(uuid4()), 'lease_id': lease,
            'candidate_id': candidate['candidate_id'], 'ok': True, 'waveform': levels})
        assert response.status_code == 200, response.text
    clock.value += 5000
    c.tick()
    current = guests[0].get(prefix + '/state').json()['game']['round']
    assert current['waveform'] == levels
    assert 'preview_url' not in current and 'audio_candidate_id' not in current


def test_searched_metadata_full_and_artist_only_answers_score_through_http(session):
    c, clock, host, guests, room, prefix, lease = session
    gid, attempt, _ = start(session)
    with c.db.read() as conn:
        current = c.game.repo.current(conn, gid)
        frozen = json.loads(c.game.repo.game(conn, gid)['songs_snapshot_json'])
        song = next(song for song in frozen if song['song_key'] == current['song_key'])
        alternate = next(dict(row) for row in conn.execute('SELECT * FROM demo_catalog')
                         if row['title'] != song['title'] and json.loads(row['artists_json'])[0]['artist_key'] == song['artists'][0]['artist_key'])
        clock.value = current['starts_at_ms'] + 1000
    c.tick()
    correct = host.get(prefix + '/song-search', params={'q': song['title']}).json()['songs'][0]['token']
    partial = guests[0].get(prefix + '/song-search', params={'q': alternate['title']}).json()['songs'][0]['token']
    path = prefix + f'/games/{gid}/rounds/{attempt["id"]}/answers'
    listeners = [listener['player_id'] for listener in song['listeners']]
    assert host.post(path, json={'song_guess_token': correct, 'who_player_ids': listeners}).status_code == 200
    assert guests[0].post(path, json={'song_guess_token': partial, 'who_player_ids': listeners}).status_code == 200
    assert guests[1].post(path, json={'song_guess_token': None, 'who_player_ids': []}).status_code == 200
    reveal = host.get(prefix + '/state').json()['game']['round']['reveal']
    own = reveal['my_answer']
    guest_answer = guests[0].get(prefix + '/state').json()['game']['round']['reveal']['my_answer']
    multiplier = {'easy': 1, 'medium': 1.5, 'hard': 2}[current['difficulty']]
    assert own['points'] == half_up(Fraction(248) * Fraction(str(multiplier)) * Fraction(3, 2))
    # 100 song + 48 rounded speed points + 100 listener points, then perfect.
    assert guest_answer['points'] == 150 * multiplier
    assert own['song_guess']['title'] == song['title']


def test_slow_catalog_lookup_does_not_hold_room_command_lock(tmp_path):
    import threading
    from concurrent.futures import ThreadPoolExecutor
    entered, release = threading.Event(), threading.Event()
    def provider(query):
        entered.set()
        assert release.wait(3)
        return [SONG]
    app = create_app(Config(tmp_path), background=False, song_search=SongSearch(provider))
    with TestClient(app) as host, TestClient(app) as searching:
        room = host.post('/api/rooms', json={'nickname': 'Host', 'mode': 'demo'}).json()
        prefix = '/api/rooms/' + room['room_id']
        assert searching.post(prefix + '/join', json={'nickname': 'Guest'}).status_code == 201
        with ThreadPoolExecutor(max_workers=2) as pool:
            pending = pool.submit(searching.get, prefix + '/song-search', params={'q': 'Billie Jean'})
            assert entered.wait(2)
            try:
                heartbeat = pool.submit(host.post, prefix + '/heartbeat', json={})
                assert heartbeat.result(timeout=1).status_code == 200
            finally:
                release.set()
            assert pending.result(timeout=2).status_code == 200
